import = ["/Users/lstrzepek/.config/alacritty/themes/nord.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.96

[window.padding]
x = 18
y = 16
